# Generated by Django 5.1.3 on 2024-12-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[
                    ("cover1", "/book_covers/cover_white.png"),
                    ("cover2", "/book_covers/cover_white.png"),
                    ("cover3", "/book_covers/cover_white.png"),
                    ("cover4", "/book_covers/cover_white.png"),
                    ("cover5", "/book_covers/cover_white.png"),
                ],
                default=("cover1", "/book_covers/cover_white.png"),
                max_length=20,
            ),
        ),
    ]
