# Generated by Django 3.2 on 2022-01-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='studylist',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='studylist',
            old_name='creator',
            new_name='created_by',
        ),
    ]
