# Generated by Django 3.2 on 2021-12-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='useremail',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
