# Generated by Django 3.2 on 2021-12-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
