# Generated by Django 3.2 on 2021-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0002_auto_20211228_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
