# Generated by Django 4.0 on 2022-01-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0002_alter_studylist_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylist',
            name='study_contect',
            field=models.TextField(max_length=3000),
        ),
    ]
