# Generated by Django 3.2 on 2021-12-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0002_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
