# Generated by Django 3.2 on 2021-12-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0002_auto_20211230_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studylist',
            old_name='category',
            new_name='category_id',
        ),
    ]
