# Generated by Django 3.2 on 2021-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0003_remove_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
