# Generated by Django 4.0 on 2022-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0003_alter_studylist_study_contect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studylist',
            name='study_contect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
