# Generated by Django 3.2 on 2021-12-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0004_auto_20211226_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
