# Generated by Django 3.2 on 2021-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviewer', '0005_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='useremail',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
